### ISSUE TITLE
Inventory item duplication when kicked/banned

### ISSUE THREAD

**Issue by EditChris** [zrdzn/GreatLifeSteal#106] opened 2022-06-24 00:26 UTC
When you use the custom actions feature to ban a player after dying with 1 heart, everything happens so fast that the items on your inventory drops, but stay on the inventory after being revived with a pardon / unban, effectively duplicating them.

It can be _fixed_ adding a "- clear {victim}" command on the parameters, but it would be appreciated that this is fixed the right way.

**Comment by zrdzn** [comment] 2022-06-25 00:06
Since we can't effectively detect if a custom command is meant to kick/ban someone because there may be many different aliases for the same command and it's bad practice to make a hardcoded check.

1. We could add a boolean property to an each action whether on its activation it should clear victim's drops, e.g.:
```YML
        eliminate:
            enabled: true
            type: DISPATCH_COMMANDS
            clearInventory: true
            parameters: 
            - tempban {victim} 7d
```
In my opinion it's the worst possible solution that can be made because custom actions are not created for ban purposes only, if you have few actions, some of them have this property set to true, some of them to false - what should we do then? It doesn't look nice either.

2. We have an action called BAN in our to-do list and it will have this duplicate 'bug' fixed internally.

3. It may be possible that it's just caused by insta-execute without any delays. We are able to add a fixed amount of ticks that it should wait before executing an action or just add delay as a property to an each action, e.g.:
```YML
        eliminate:
            enabled: true
            type: DISPATCH_COMMANDS
            delay: 5
            parameters: 
            - tempban {victim} 7d
```
If this property would solve this issue, I'd rather add that. I'll test that soon and let you know about my decision.

**Comment by EditChris** [comment] 2022-06-25 00:20
I think the delay property could be the closest to a nice solution.

One idea I had about fixing this is to, instead of doing that action at the death event, do it on the respawn event. But that actually could be an issue because exiting The End though the portal on the dragon island could trigger the action because it uses that event too for some reason.

The delay thing could work, because in the action that I configured to ban the player after dying with 1 heart, I could set a delay of 1 (if that's in seconds) so the items on the inventory drops just before the execution of the action.

About the clear inventory property, in my opinion isn't really needed because one can just add the command to the parameters, and that's it. That's even better because you can put the command before/after some other action giving you more flexibility. The delay thing is nice, it actually adds even more value to the custom actions part of this plugin.

**Closed** 2022-06-25 18:51 UTC
Labels: bug, enhancement
